# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tanzim Saqib
email: me@tanzimsaqib.com
description: > #
  I'm a Microsoft Alumni and an international award-winning 11-year experienced polyglot 
  technologist. I bring expertise on both proprietary and open source stack with 
  the speciality of designing and deploying secure, complex and scalable solutions. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tanzimsaqib.com" # the base hostname & protocol for your site
twitter_username: tanzimsaqib
github_username:  tsaqib

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
