# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tanzim Saqib
email: me@tanzimsaqib.com
description: > 
  I'm a polyglot technical leader in art, crafts, science and engineering of software 
  development with the speciality of designing and delivering complex and scalable solutions. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://tanzimsaqib.com" # the base hostname & protocol for your site
twitter_username: tanzimsaqib
github_username:  tsaqib

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

twitter:
  username: tanzimsaqib
facebook:
  app_id: 1567505306889164

sass:
  style: :compressed